using System.Diagnostics;
using System.Drawing.Drawing2D;
using RyzoriaUI.Config;
using RyzoriaUI.Core;
using RyzoriaUI.Models;
using RyzoriaUI.Services;

namespace RyzoriaUI.UI;

public sealed class MainForm : Form
{
    private readonly Color Bg=Color.FromArgb(8,11,18), Panel=Color.FromArgb(16,23,34), Primary=Color.FromArgb(22,119,255), Muted=Color.FromArgb(148,163,184);
    private readonly AppSettings _settings=SettingsStore.Load();
    private readonly EmbeddedToolManager _tools;
    private readonly AdbService _adb;
    private readonly ScrcpyService _scrcpy;
    private readonly FileTransferService _files;
    private readonly DiagnosticsService _diag;
    private readonly MapperService _mapper=new();
    private readonly ResourceStats _stats;
    private readonly Panel _content=new(), _start=new();
    private readonly Label _deviceStatus=new(),_resource=new(),_clock=new();
    private readonly ComboBox _deviceBox=new();
    private IReadOnlyList<AndroidDevice> _devices=Array.Empty<AndroidDevice>();
    private string _page="Dashboard";
    private System.Threading.Timer? _deviceTimer;

    public MainForm()
    {
        Text="RyzoriaUI v1.7"; StartPosition=FormStartPosition.CenterScreen; MinimumSize=new Size(980,620); BackColor=Bg; ForeColor=Color.White; FormBorderStyle=FormBorderStyle.None;
        WindowState=FormWindowState.Maximized;
        _tools=new EmbeddedToolManager(); _adb=new AdbService(_tools); _scrcpy=new ScrcpyService(_tools); _files=new FileTransferService(_tools); _diag=new DiagnosticsService(_tools,_adb); _stats=new ResourceStats();
        FormClosing += (_,_)=>{_deviceTimer?.Dispose();_scrcpy.Dispose();_stats.Dispose();_tools.Dispose();};
        BuildShell(); ShowDashboard(); StartPolling();
    }

    private void BuildShell()
    {
        var top=new Panel{Dock=DockStyle.Top,Height=54,BackColor=Panel}; Controls.Add(top);
        var brand=LabelText("RYZORIAUI  v1.7",18,16,FontStyle.Bold,16); brand.Click+=(_,_)=>ShowDashboard(); top.Controls.Add(brand);
        var search=TextBoxStyled("Search RyzoriaUI...",250,12,270); search.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){ShowSearch(search.Text);e.SuppressKeyPress=true;}}; top.Controls.Add(search);
        var min=new Button{Text="—",FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=Panel,Location=new Point(Width-150,8),Size=new Size(42,36),Anchor=AnchorStyles.Top|AnchorStyles.Right}; min.Click+=(_,_)=>WindowState=FormWindowState.Minimized; top.Controls.Add(min);
        var max=new Button{Text="□",FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=Panel,Location=new Point(Width-102,8),Size=new Size(42,36),Anchor=AnchorStyles.Top|AnchorStyles.Right}; max.Click+=(_,_)=>WindowState=WindowState==FormWindowState.Maximized?FormWindowState.Normal:FormWindowState.Maximized; top.Controls.Add(max);
        var close=new Button{Text="×",FlatStyle=FlatStyle.Flat,ForeColor=Color.White,BackColor=Color.FromArgb(120,20,30),Location=new Point(Width-54,8),Size=new Size(42,36),Anchor=AnchorStyles.Top|AnchorStyles.Right}; close.Click+=(_,_)=>Close(); top.Controls.Add(close);

        var sidebar=new Panel{Dock=DockStyle.Left,Width=190,BackColor=Color.FromArgb(10,15,24)}; Controls.Add(sidebar);
        string[] nav={"⌂  Home","📱 Android Hub","📁 File Manager","🎮 Gaming Center","🎯 Control Mapper","⚡ Performance","🩺 Diagnostics","🧪 Developer","⚙  Settings","ⓘ About"};
        int y=74; foreach(var n in nav){var b=NavButton(n,y);sidebar.Controls.Add(b);y+=48;}

        _content.Dock=DockStyle.Fill; _content.Padding=new Padding(22); _content.BackColor=Bg; Controls.Add(_content);
        var bottom=new Panel{Dock=DockStyle.Bottom,Height=36,BackColor=Panel}; Controls.Add(bottom);
        _deviceStatus.Text="● ADB: checking"; _deviceStatus.ForeColor=Color.Gold; _deviceStatus.Location=new Point(14,9); _deviceStatus.AutoSize=true; bottom.Controls.Add(_deviceStatus);
        _resource.Location=new Point(220,9); _resource.AutoSize=true; _resource.ForeColor=Muted; bottom.Controls.Add(_resource);
        _clock.Location=new Point(Width-120,9); _clock.AutoSize=true; _clock.Anchor=AnchorStyles.Right|AnchorStyles.Bottom; bottom.Controls.Add(_clock);
        var clockTimer=new System.Windows.Forms.Timer{Interval=1000};clockTimer.Tick+=(_,_)=>_clock.Text=DateTime.Now.ToString("HH:mm:ss  dd/MM/yyyy");clockTimer.Start();
        _stats.Updated+=()=>BeginInvoke(()=>_resource.Text=$"CPU {(_stats.CpuPercent):0}%  •  App {_stats.AppMemoryMb:0} MB");
    }

    private Button NavButton(string text,int y){var b=new Button{Text=text,Location=new Point(12,y),Size=new Size(166,42),TextAlign=ContentAlignment.MiddleLeft,FlatStyle=FlatStyle.Flat,BackColor=Color.Transparent,ForeColor=Color.White,Padding=new Padding(12,0,0,0)};b.FlatAppearance.BorderSize=0;b.Click+=(_,_)=>{if(text.Contains("Home"))ShowDashboard();else if(text.Contains("Android"))ShowAndroid();else if(text.Contains("File"))ShowFiles();else if(text.Contains("Gaming"))ShowGaming();else if(text.Contains("Mapper"))ShowMapper();else if(text.Contains("Performance"))ShowPerformance();else if(text.Contains("Diagnostics"))ShowDiagnostics();else if(text.Contains("Developer"))ShowDeveloper();else if(text.Contains("Settings"))ShowSettings();else ShowAbout();};return b;}
    private Label LabelText(string t,int x,int y,FontStyle fs=FontStyle.Regular,float size=10)=>new(){Text=t,Location=new Point(x,y),AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",size,fs)};
    private TextBox TextBoxStyled(string ph,int x,int y,int w)=>new(){Text="",PlaceholderText=ph,Location=new Point(x,y),Width=w,BackColor=Color.FromArgb(24,31,43),ForeColor=Color.White,BorderStyle=BorderStyle.FixedSingle};
    private Panel Card(int x,int y,int w,int h){return new Panel{Location=new Point(x,y),Size=new Size(w,h),BackColor=Panel};}
    private Button Btn(string text,int x,int y,int w=150){var b=new Button{Text=text,Location=new Point(x,y),Size=new Size(w,38),FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(20,33,55),ForeColor=Color.White};b.FlatAppearance.BorderColor=Primary;return b;}
    private void ResetContent(string title){_content.Controls.Clear();_page=title;_content.Controls.Add(LabelText(title,10,0,FontStyle.Bold,22));}

    private void ShowDashboard(){ResetContent("RyzoriaUI Desktop");var hero=Card(10,48,700,180);_content.Controls.Add(hero);hero.Controls.Add(LabelText("ANDROID DESKTOP EXPERIENCE",20,20,FontStyle.Bold,18));hero.Controls.Add(LabelText("Android • ADB • scrcpy • Gaming • Files",20,55,FontStyle.Regular,11));hero.Controls.Add(LabelText("Target mode: Celeron N2040 + 4 GB RAM",20,82,FontStyle.Regular,10));var start=Btn("Open Android Hub",20,118,180);start.Click+=(_,_)=>ShowAndroid();hero.Controls.Add(start);var perf=Btn("Ultra Low Mode",215,118,150);perf.Click+=(_,_)=>ApplyPreset("Ultra Low");hero.Controls.Add(perf);var reload=Btn("Test Connection",380,118,150);reload.Click+=async(_,_)=>await RefreshDevices();hero.Controls.Add(reload);}

    private void ShowAndroid(){ResetContent("Android Hub");var card=Card(10,48,780,400);_content.Controls.Add(card);card.Controls.Add(LabelText("Connected device",18,18,FontStyle.Bold,13));_deviceBox.Location=new Point(18,48);_deviceBox.Width=420;_deviceBox.BackColor=Color.FromArgb(24,31,43);_deviceBox.ForeColor=Color.White;_deviceBox.DropDownStyle=ComboBoxStyle.DropDownList;card.Controls.Add(_deviceBox);var refresh=Btn("↻ Refresh",460,46,120);refresh.Click+=async(_,_)=>await RefreshDevices();card.Controls.Add(refresh);var mirror=Btn("START MIRROR",18,94,160);mirror.Click+=async(_,_)=>await StartMirror();card.Controls.Add(mirror);var stop=Btn("STOP",190,94,100);stop.Click+=(_,_)=>_scrcpy.Stop();card.Controls.Add(stop);
        int y=145; foreach(var a in new[]{("Home",(Func<string,Task>)(_adb.HomeAsync)),("Back",_adb.BackAsync),("Recent",_adb.RecentAsync),("Vol +",_adb.VolumeUpAsync),("Vol -",_adb.VolumeDownAsync),("Mute",_adb.MuteAsync),}){var b=Btn(a.Item1,18+(y-145)/52*112,y,104);b.Click+=async(_,_)=>await DeviceAction(a.Item2);card.Controls.Add(b);if((y-145)/52>=4)y=197;else y+=52;}
        var info=LabelText("No device loaded.",18,220,FontStyle.Regular,10);info.MaximumSize=new Size(730,150);card.Controls.Add(info);async Task UpdateInfo(){var d=SelectedDevice();if(d is null){info.Text="No authorized Android device. Enable USB debugging and accept the RSA prompt.";return;}info.Text=$"MODEL      {d.Manufacturer} {d.Model}\nCODE       {d.DeviceCode}\nANDROID    {d.AndroidVersion} (SDK {d.Sdk})\nBATTERY    {d.Battery}\nRAM        {d.Ram}\nSTORAGE    {d.Storage}\nDISPLAY    {d.Resolution} / DPI {d.Dpi}\nCONNECTION {d.ConnectionType}\nADB        {(d.Authorized?"Connected":"Unauthorized")}";}
        _=UpdateInfo();
        var shot=Btn("Screenshot",18,350,130);shot.Click+=async(_,_)=>await TakeScreenshot();card.Controls.Add(shot);var reboot=Btn("Reboot",158,350,110);reboot.Click+=async(_,_)=>await DeviceAction(_adb.RebootAsync);card.Controls.Add(reboot);
    }

    private void ShowFiles(){ResetContent("Android File Manager");var card=Card(10,48,790,420);_content.Controls.Add(card);var path=TextBoxStyled("Remote path e.g. /sdcard/Download",18,18,470);path.Text="/sdcard";card.Controls.Add(path);var list=Btn("List",500,18,100);card.Controls.Add(list);var output=new RichTextBox{Location=new Point(18,70),Size=new Size(745,260),BackColor=Color.Black,ForeColor=Color.LightGreen,Font=new Font("Consolas",9),ReadOnly=true};card.Controls.Add(output);list.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null){output.Text="No device.";return;}output.Text=await _files.ListAsync(d.Serial,string.IsNullOrWhiteSpace(path.Text)?"/sdcard":path.Text);};var pull=Btn("Pull file",18,346,120);pull.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null)return;using var ofd=new SaveFileDialog();if(ofd.ShowDialog()!=DialogResult.OK)return;var remote=path.Text.Trim();if(await _files.PullAsync(d.Serial,remote,ofd.FileName))MessageBox.Show("Transfer complete.");};card.Controls.Add(pull);var push=Btn("Push file",150,346,120);push.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null)return;using var ofd=new OpenFileDialog();if(ofd.ShowDialog()!=DialogResult.OK)return;var remote=path.Text.Trim();if(await _files.PushAsync(d.Serial,ofd.FileName,remote))MessageBox.Show("Upload complete.");};card.Controls.Add(push);var folder=Btn("Create folder",282,346,120);folder.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null)return;var name=Prompt("Folder name", "NewFolder");if(!string.IsNullOrWhiteSpace(name))await _files.ShellAsync(d.Serial,"mkdir","-p",$"{path.Text.TrimEnd('/')}/{name}");};card.Controls.Add(folder);}

    private void ShowGaming(){ResetContent("Gaming Center");var card=Card(10,48,790,350);_content.Controls.Add(card);card.Controls.Add(LabelText("Low-end gaming profiles",18,18,FontStyle.Bold,13));var presets=new[]{"Ultra Low • 480p / 20 FPS / 2 Mbps","Low • 576p / 25 FPS / 3 Mbps","Balanced • 720p / 30 FPS / 4 Mbps","Performance • 1080p / 60 FPS / 8 Mbps"};var combo=new ComboBox{Location=new Point(18,52),Width=520,DropDownStyle=ComboBoxStyle.DropDownList};combo.Items.AddRange(presets);combo.SelectedIndex=0;card.Controls.Add(combo);var fs=new CheckBox{Text="Fullscreen",Location=new Point(18,96),AutoSize=true};card.Controls.Add(fs);var audio=new CheckBox{Text="No audio (recommended for N2040)",Location=new Point(18,126),AutoSize=true,Checked=true};card.Controls.Add(audio);var launch=Btn("Launch Mirror",18,164,150);launch.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null){MessageBox.Show("Connect Android first.");return;}var idx=Math.Max(0,combo.SelectedIndex);var p=idx switch{0=>new PerformancePreset("Ultra Low",480,20,2,true),1=>new PerformancePreset("Low",576,25,3,true),2=>new PerformancePreset("Balanced",720,30,4,true),_=>new PerformancePreset("Performance",1080,60,8,false)};await _scrcpy.StartAsync(d,p,fs.Checked,false,audio.Checked);};card.Controls.Add(launch);card.Controls.Add(LabelText("FPS counter / game performance depends on the Android device and scrcpy window. RyzoriaUI never fabricates FPS values.",18,220,FontStyle.Regular,10));}

    private void ShowMapper(){ResetContent("Universal Control Mapper");var card=Card(10,48,790,390);_content.Controls.Add(card);card.Controls.Add(LabelText("Profile",18,18,FontStyle.Bold,13));var profiles=_settings.MapperProfiles;var combo=new ComboBox{Location=new Point(18,48),Width=260,DropDownStyle=ComboBoxStyle.DropDownList};combo.Items.AddRange(profiles.Select(p=>p.Name).ToArray());combo.SelectedIndex=0;card.Controls.Add(combo);var list=new ListBox{Location=new Point(18,92),Size=new Size(350,220),BackColor=Color.FromArgb(10,15,24),ForeColor=Color.White};card.Controls.Add(list);void Load(){list.Items.Clear();var p=profiles[Math.Max(0,combo.SelectedIndex)];foreach(var kv in p.Bindings)list.Items.Add($"{kv.Key}  →  {kv.Value}");}combo.SelectedIndexChanged+=(_,_)=>Load();Load();var add=Btn("Test binding",390,94,150);add.Click+=async(_,_)=>{var d=SelectedDevice();if(d is null||list.SelectedItem is null)return;var key=list.SelectedItem.ToString()!.Split('→')[0].Trim();var p=profiles[Math.Max(0,combo.SelectedIndex)];if(p.Bindings.TryGetValue(key,out var bind))await _mapper.SendBindingAsync(_adb,d.Serial,bind);};card.Controls.Add(add);var note=LabelText("Mappings use ADB input events where possible. Touch injection is device/game dependent; no universal 100% guarantee.",390,155,FontStyle.Regular,10);note.MaximumSize=new Size(330,100);card.Controls.Add(note);var save=Btn("Save JSON",390,275,150);save.Click+=(_,_)=>{SettingsStore.Save(_settings);MessageBox.Show("Mapper profiles saved.");};card.Controls.Add(save);}

    private void ShowPerformance(){ResetContent("Performance Manager");var modes=new[]{("Auto",480,20,2),("Ultra Low",480,20,2),("Low",576,25,3),("Balanced",720,30,4),("Performance",1080,60,8)};int y=52;foreach(var m in modes){var b=Btn($"{m.Item1} • {m.Item2}p / {m.Item3} FPS",10,y,260);var mode=m;b.Click+=(_,_)=>{_settings.PerformanceMode=mode.Item1;_settings.ScrcpyMaxSize=mode.Item2;_settings.ScrcpyMaxFps=mode.Item3;_settings.ScrcpyBitrateMbps=mode.Item4;_settings.NoAudio=mode.Item1!="Performance";SettingsStore.Save(_settings);MessageBox.Show($"Performance: {mode.Item1}");};_content.Controls.Add(b);y+=50;}_content.Controls.Add(LabelText("Auto is intentionally conservative on the N2040 / 4 GB target: 480p, 20 FPS and 2 Mbps with audio off.",310,62));}

    private async void ShowDiagnostics(){ResetContent("Diagnostics Center");var card=Card(10,48,790,400);_content.Controls.Add(card);var outp=new RichTextBox{Location=new Point(18,62),Size=new Size(750,300),BackColor=Color.Black,ForeColor=Color.LightGreen,Font=new Font("Consolas",10),ReadOnly=true};card.Controls.Add(outp);var run=Btn("TEST AGAIN",18,18,150);run.Click+=async(_,_)=>await Run();card.Controls.Add(run);async Task Run(){outp.Text="RYZORIA DIAGNOSTICS\r\n\r\nRunning...\r\n";var r=await _diag.RunAsync();outp.Text="RYZORIA DIAGNOSTICS\r\n\r\n"+string.Join("\r\n",r.Select(kv=>$"{kv.Key,-20} {kv.Value}"));}await Run();}

    private void ShowDeveloper(){ResetContent("Developer Console");var card=Card(10,48,820,430);_content.Controls.Add(card);var input=TextBoxStyled("Enter whitelisted command",18,18,570);card.Controls.Add(input);var output=new RichTextBox{Location=new Point(18,68),Size=new Size(770,300),BackColor=Color.Black,ForeColor=Color.LightGreen,Font=new Font("Consolas",9),ReadOnly=true};card.Controls.Add(output);input.KeyDown+=async(_,e)=>{if(e.KeyCode!=Keys.Enter)return;e.SuppressKeyPress=true;var cmd=input.Text.Trim();input.Clear();output.AppendText($"> {cmd}\r\n");try{switch(cmd.ToLowerInvariant()){case "help":output.AppendText("adb.version  adb.devices  device.info  device.battery  device.resolution  connection.test  diagnostics.run  logs.show  settings.reset  clear\r\n");break;case "adb.version":output.AppendText(await _adb.VersionAsync()+"\r\n");break;case "adb.devices":foreach(var d in await _adb.GetDevicesAsync())output.AppendText($"{d.Serial}\t{d.State}\t{d.Model}\t{d.ConnectionType}\r\n");break;case "device.info":output.AppendText(SelectedDevice()?.ToString()+"\r\n"??"No device\r\n");break;case "device.battery":output.AppendText(SelectedDevice()?.Battery+"\r\n"??"No device\r\n");break;case "device.resolution":output.AppendText(SelectedDevice()?.Resolution+"\r\n"??"No device\r\n");break;case "connection.test":output.AppendText((await _diag.RunAsync()).GetValueOrDefault("Android Device","unknown")+"\r\n");break;case "diagnostics.run":output.AppendText(string.Join("\r\n",await _diag.RunAsync())+"\r\n");break;case "logs.show":var lp=Path.Combine(SettingsStore.LogDirectory,"ryzoria.log");output.AppendText(File.Exists(lp)?File.ReadAllText(lp):"No log file.\r\n");break;case "settings.reset":SettingsStore.Reset();output.AppendText("Settings reset. Restart recommended.\r\n");break;case "clear":output.Clear();break;default:output.AppendText("Command rejected. Type help.\r\n");break;}}catch(Exception ex){output.AppendText(ex.Message+"\r\n");}};}

    private void ShowSettings(){ResetContent("Settings");var card=Card(10,48,790,390);_content.Controls.Add(card);var dev=new CheckBox{Text="Developer Mode",Checked=_settings.DeveloperMode,Location=new Point(18,24),AutoSize=true};dev.CheckedChanged+=(_,_)=>{_settings.DeveloperMode=dev.Checked;SettingsStore.Save(_settings);};card.Controls.Add(dev);var auto=new CheckBox{Text="Auto reconnect",Checked=_settings.AutoReconnect,Location=new Point(18,55),AutoSize=true};auto.CheckedChanged+=(_,_)=>{_settings.AutoReconnect=auto.Checked;SettingsStore.Save(_settings);};card.Controls.Add(auto);var clip=new CheckBox{Text="Clipboard sync (best effort)",Checked=_settings.ClipboardSync,Location=new Point(18,86),AutoSize=true};clip.CheckedChanged+=(_,_)=>{_settings.ClipboardSync=clip.Checked;SettingsStore.Save(_settings);};card.Controls.Add(clip);var notif=new CheckBox{Text="Android notifications (best effort)",Checked=_settings.Notifications,Location=new Point(18,117),AutoSize=true};notif.CheckedChanged+=(_,_)=>{_settings.Notifications=notif.Checked;SettingsStore.Save(_settings);};card.Controls.Add(notif);var backup=Btn("Backup settings",18,165,150);backup.Click+=(_,_)=>{using var s=new SaveFileDialog{Filter="JSON|*.json",FileName="ryzoria-settings.json"};if(s.ShowDialog()==DialogResult.OK)File.Copy(SettingsStore.SettingsFile,s.FileName,true);};card.Controls.Add(backup);var restore=Btn("Restore settings",180,165,150);restore.Click+=(_,_)=>{using var o=new OpenFileDialog{Filter="JSON|*.json"};if(o.ShowDialog()==DialogResult.OK){File.Copy(o.FileName,SettingsStore.SettingsFile,true);MessageBox.Show("Restored. Restart RyzoriaUI.");}};card.Controls.Add(restore);var reset=Btn("Reset all",342,165,130);reset.Click+=(_,_)=>{SettingsStore.Reset();MessageBox.Show("Reset complete. Restart RyzoriaUI.");};card.Controls.Add(reset);card.Controls.Add(LabelText("Single-exe distribution: ADB + scrcpy are embedded and extracted only to a temporary session folder while running.",18,235));}

    private void ShowAbout(){ResetContent("About RyzoriaUI");_content.Controls.Add(LabelText("RYZORIAUI",10,52,FontStyle.Bold,28));_content.Controls.Add(LabelText("v1.7 • Android Desktop Experience",10,95,FontStyle.Regular,13));_content.Controls.Add(LabelText("Developed by Riyzz",10,135));_content.Controls.Add(LabelText("github.com/riyzzmcganteng",10,160));_content.Controls.Add(LabelText("Pengembangan Riyzz / Belajar pemula menjadi pro",10,185));_content.Controls.Add(LabelText("Designed for low-end Windows PCs such as Celeron N2040 + 4 GB RAM.",10,230));}

    private void ShowSearch(string q){if(string.IsNullOrWhiteSpace(q)){ShowDashboard();return;}var m=q.ToLowerInvariant();if(m.Contains("android")||m.Contains("adb"))ShowAndroid();else if(m.Contains("file"))ShowFiles();else if(m.Contains("game"))ShowGaming();else if(m.Contains("map"))ShowMapper();else if(m.Contains("diag"))ShowDiagnostics();else if(m.Contains("setting"))ShowSettings();else MessageBox.Show("No RyzoriaUI page matched the search.");}

    private AndroidDevice? SelectedDevice()=>_devices.Count==0?null:(_deviceBox.SelectedIndex>=0&&_deviceBox.SelectedIndex<_devices.Count?_devices[_deviceBox.SelectedIndex]:_devices.FirstOrDefault(x=>x.Authorized));
    private async Task RefreshDevices(){try{_devices=await _adb.GetDevicesAsync();_deviceBox.Items.Clear();foreach(var d in _devices)_deviceBox.Items.Add($"{d.Model} • {d.Serial} • {d.State}");if(_devices.Count>0)_deviceBox.SelectedIndex=0;_deviceStatus.Text=_devices.Any(x=>x.Authorized)?$"● Android: {_devices.Count(x=>x.Authorized)} connected":"● Android: not connected";_deviceStatus.ForeColor=_devices.Any(x=>x.Authorized)?Color.LightGreen:Color.Gold;Logger.Info($"Device scan: {_devices.Count}");}catch(Exception ex){_deviceStatus.Text="● ADB: error";_deviceStatus.ForeColor=Color.Red;Logger.Error(ex.ToString());}}
    private async Task DeviceAction(Func<string,Task> action){var d=SelectedDevice();if(d is null){MessageBox.Show("Connect and authorize an Android device first.");return;}try{await action(d.Serial);}catch(Exception ex){MessageBox.Show(ex.Message,"RyzoriaUI",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private async Task StartMirror(){var d=SelectedDevice();if(d is null){MessageBox.Show("Connect and authorize an Android device first.");return;}var p=new PerformancePreset("Current",_settings.ScrcpyMaxSize,_settings.ScrcpyMaxFps,_settings.ScrcpyBitrateMbps,_settings.NoAudio);try{await _scrcpy.StartAsync(d,p,_settings.Fullscreen,_settings.TurnScreenOff,_settings.NoAudio);}catch(Exception ex){MessageBox.Show(ex.Message);}}
    private void ApplyPreset(string name){if(name=="Ultra Low"){_settings.PerformanceMode=name;_settings.ScrcpyMaxSize=480;_settings.ScrcpyMaxFps=20;_settings.ScrcpyBitrateMbps=2;_settings.NoAudio=true;SettingsStore.Save(_settings);}}
    private async Task TakeScreenshot(){var d=SelectedDevice();if(d is null)return;using var s=new SaveFileDialog{Filter="PNG|*.png",FileName="ryzoria-screenshot.png"};if(s.ShowDialog()!=DialogResult.OK)return;try{var ok=await _adb.ScreenshotAsync(d.Serial,s.FileName);MessageBox.Show(ok?"Screenshot saved.":"Screenshot failed.");}catch(Exception ex){MessageBox.Show(ex.Message);}}
    private void StartPolling(){_ = RefreshDevices();_deviceTimer=new System.Threading.Timer(async _=>{if(_settings.AutoReconnect){try{_devices=await _adb.GetDevicesAsync();}catch{}}},null,3000,8000);}
    private static string? Prompt(string title,string defaultValue){using var f=new Form{Text=title,StartPosition=FormStartPosition.CenterParent,Width=360,Height=150,BackColor=Color.FromArgb(16,23,34),ForeColor=Color.White,FormBorderStyle=FormBorderStyle.FixedDialog};var t=new TextBox{Left=16,Top=18,Width=310,Text=defaultValue,BackColor=Color.FromArgb(24,31,43),ForeColor=Color.White};var ok=new Button{Text="OK",Left=168,Top=58,Width=75,DialogResult=DialogResult.OK};var cancel=new Button{Text="Cancel",Left=251,Top=58,Width=75,DialogResult=DialogResult.Cancel};f.Controls.AddRange(new Control[]{t,ok,cancel});f.AcceptButton=ok;f.CancelButton=cancel;return f.ShowDialog()==DialogResult.OK?t.Text:null;}
}
